### ISSUE TITLE
Working DAE example

### ISSUE THREAD

**Issue by ryakoub** [SciML/DifferentialEquations.jl#630]
Hello,

I am unable to get a DAE example to work, neither the one in the docs nor the one included example problems.  I appreciate it if you can check both of them and let me know what could be wrong.  I tried Julia 1.2 and 1.4.2

**Comment by ChrisRackauckas** [comment]
Hey,

https://docs.sciml.ai/latest/tutorials/dae_example/ should be fine with the latest Sundials patch.

```julia
function f(out,du,u,p,t)
  out[1] = - 0.04u[1]              + 1e4*u[2]*u[3] - du[1]
  out[2] = + 0.04u[1] - 3e7*u[2]^2 - 1e4*u[2]*u[3] - du[2]
  out[3] = u[1] + u[2] + u[3] - 1.0
end
u₀ = [1.0, 0, 0]
du₀ = [-0.04, 0.04, 0.0]
tspan = (0.0,100000.0)

using DifferentialEquations
differential_vars = [true,true,false]
prob = DAEProblem(f,du₀,u₀,tspan,differential_vars=differential_vars)

using Sundials
sol = solve(prob,IDA())

using Plots
plot(sol, xscale=:log10, tspan=(1e-6, 1e5), layout=(3,1))
```

We had a hiccup for about 12 hours due to a bad patch that effected 64-bit Windows. See https://discourse.julialang.org/t/methoderror-no-method-matching-unsafe-convert-type-ptr-int32-base-refvalue-int64/42424 for more details. Sorry about that!
