### ISSUE TITLE
Event detection not continuously/not always triggering

### ISSUE THREAD

**Issue by dmillard** [SciML/DifferentialEquations.jl#696]
I have an inelastic version of the bouncing ball example, where I would like the ball to make contact with the ground and stick there until some other dynamics pulls it away. Chris Rackauckas suggested in slack that I post an issue here.

```julia
function dynamics!(du, u, p, t)
	du[:, 1] .= u[:, 2]
	du[:, 2] .= (0, -9.8)
end
floor_cond(u, t, int) = u[2, 1] + 1
floor_aff!(int) = int.u[2, 2] = 0
floor_event = ContinuousCallback(floor_cond, floor_aff!)
u0 = [0 1; 0 1]
prob = ODEProblem{true}(dynamics!, u0, (0., 2.))
sol = DifferentialEquations.solve(prob, callback=floor_event)
plot(sol, vars=[(1, 2)])
```

![inelastic](https://user-images.githubusercontent.com/757949/100493067-68eca680-3101-11eb-82e7-e627577ac32c.png)

Also, while investigating, I found that even setting the bounce with a smaller coefficient of restitution ends up with the ball falling through the floor after a while, which you can see here:

```julia
floor_cond(u, t, int) = u[2, 1] + 1
floor_aff!(int) = int.u[2, 2] *= -0.5
floor_event = ContinuousCallback(floor_cond, floor_aff!)
```

![slightly_elastic](https://user-images.githubusercontent.com/757949/100493050-32169080-3101-11eb-89f6-346c79c3aab2.png)

Thank you!

**Comment by ChrisRackauckas** [comment]
@kanav99 let's add this to the tests on DiffEqBase master and see if that fix also handled this case.

**Comment by ChrisRackauckas** [comment]
The workaround is to decrease the maximum dt though. The issue is that dt->infinity because the integrator can handle this problem with 100% accuracy. But as dt grows, the floating point errors in the rootfinding magnify as dt->infinity which cases the issue at some point. Putting a maximum on that stops the issue. So it really boils down to the fact that the ODE is too easy to stop dt growth.

**Comment by dmillard** [comment]
Thank you for your reply. Unfortunately I see effectively the same behavior, with `dtmax=1e-4`. Here's the full snippet:

```julia
using DifferentialEquations, Plots

function dynamics!(du, u, p, t)
	du[:, 1] .= u[:, 2]
	du[:, 2] .= (0, -9.8)
end

floor_cond(u, t, int) = u[2, 1] + 1
floor_aff!(int) = int.u[2, 2] = 0
floor_event = ContinuousCallback(floor_cond, floor_aff!)

u0 = [0 1; 0 1]
prob = ODEProblem{true}(dynamics!, u0, (0., 2.))
sol = solve(prob, callback=floor_event; dtmax=1e-4)
fig = plot(sol, vars=[(1, 2)])
```

And the resulting plot:
![inelastic_contact](https://user-images.githubusercontent.com/757949/100524745-9af51b80-3188-11eb-95ba-3e9a807f4726.png)


I realize I neglected to include my Pkg status:
```
pkg> st
Status `~/projects/BouncyContact/Project.toml`
  [2b5f629d] DiffEqBase v6.48.3 `https://github.com/SciML/DiffEqBase.jl.git#master`
  [0c46a032] DifferentialEquations v6.15.0
  [91a5bcdd] Plots v1.9.1
  [c3e4b0f8] Pluto v0.12.14
```

It makes sense to me that after some time the steps will be too small regardless of the `dtmax`. However for the inelastic case even this seems like it may not be the right solution. Is there some other way these problems are typically handled?

With a hand-written forward Euler, I can do:

```julia
using Plots

function dynamics!(du, u, p, t)
	du[:, 1] .= u[:, 2]
	du[:, 2] .= (0, -9.8)
end

dt = 1e-3
u = Float64[0 1; 0 1]
du = zero(u)
xs, ys = Float64[], Float64[]
for t ∈ 0:dt:2
	dynamics!(du, u, nothing, nothing)
	u .+= dt .* du
	if u[2, 1] < -1
		u[2, 2] = 0
	end
	push!(xs, u[1, 1])
	push!(ys, u[2, 1])
end
fig = plot(xs, ys)
```

Which yields:
![handwritten_euler_contact](https://user-images.githubusercontent.com/757949/100524695-2e7a1c80-3188-11eb-99da-7724ce2af2fd.png)

Of course, I'd rather not use my own solver, and would like to use the broader SciML ecosystem for my problems, particularly sensitivity analysis and pre-tested IMEX solvers.

**Comment by ChrisRackauckas** [comment]
You didn't write the same system. 

```julia
	if u[2, 1] < -1
		u[2, 2] = 0
	end
```

is "for any instance where `u[2, 1] < -1`, then `u[2, 2] = 0`". Meanwhile `floor_cond(u, t, int) = u[2, 1] + 1` if `u[2,1]` crosses the line -1, then `floor_aff!(int) = int.u[2, 2] = 0` make `u[2,2]=0`. But that only happens when you cross the line. After that, `du[:, 2] .= (0, -9.8)` there is a constant derivative on `u[2,2]`, so obviously it's not going to stay zero and you'll get the behavior that you see. Did you mean to write:

```julia
function dynamics!(du, u, p, t)
	du[:, 1] .= u[:, 2]
	du[:, 2] .= (0, p)
end

function floor_aff!(int)
  int.u[2, 2] = 0
  int.p = 0
end
```

?

**Comment by dmillard** [comment]
I see the point, thank you for the clarification! I am looking for something along those lines. The real problem I have is a contact problem in a robotic mechanics simulation: some surfaces make contact and there are frictional and normal forces between them. In this reduced example, I am only trying to model the non-penetration effect for a single point.

I'll have to think about how to reformulate the problem a bit, your pointer to changing parameters during the event is quite helpful. These contact problems are usually solved with impulse-level corrections at the end of timesteps, so maybe I'm trying to take a fundamentally fixed timestep approach and apply it where it doesn't belong.

In regard to the other problem of a semi-elastically bouncing ball, which may still be relevant for this bug topic, I do see the same behavior with a `dtmax` and a restitution coefficient of 0.5:
```julia
function dynamics!(du, u, p, t)
	du[:, 1] .= u[:, 2]
	du[:, 2] .= (0, -9.8)
end

floor_cond(u, t, int) = u[2, 1] + 1
floor_aff!(int) = int.u[2, 2] *= -0.5
floor_event = ContinuousCallback(floor_cond, floor_aff!)

u0 = [0 1; 0 1]
prob = ODEProblem{true}(dynamics!, u0, (0., 2.))
sol = solve(prob, callback=floor_event; dtmax=1e-4)
fig = plot(sol, vars=[(1, 2)])
```

![less_elastic_contact](https://user-images.githubusercontent.com/757949/100534270-0071f800-31db-11eb-9393-53e2c12b2862.png)

**Comment by ChrisRackauckas** [comment]
Is that using DiffEqBase master?

**Comment by dmillard** [comment]
I think so, here is my Pkg status for this project.

```
pkg> st
Status `~/projects/BouncyContact/Project.toml`
  [2b5f629d] DiffEqBase v6.48.3 `https://github.com/SciML/DiffEqBase.jl.git#master`
  [0c46a032] DifferentialEquations v6.15.0
  [91a5bcdd] Plots v1.9.1
  [c3e4b0f8] Pluto v0.12.14
```

**Comment by ChrisRackauckas** [comment]
@kanav99 should take a look during the next week.

**Comment by kanav99** [comment]
I think I understand the issue. Let's assume that the initial period of bounce is about 0.5 seconds. This interval is halved by every bounce, so the bounces happen at t = 0.5, 0.5 + 0.25, 0.5 + 0.25 + 0.125, ...... so by t = 1, there are going to be infinite bounces. This should technically make the integrator go on infinitely, but due to floating-point issues, it misses the event detection and causes the ball to go below ground, and then the integrator finishes.
I don't see any implementation fix of this. But yeah as Chris said, you should modify `p` to make it stick.

**Comment by dmillard** [comment]
Hi @kanav99, thanks for your input!

I am surely not as familiar with the internals of DifferentialEquations.jl as you are, but looking at the solution that is plotted above there is clearly a point at which the condition function crosses zero. I'm not sure I see the connection to floating point discretization, but again I'm not familiar with the way this is implemented internally.

Since my actual problem is somewhat more complex (the `p` trick would be quite a bit more tricky), I'll probably stick with a handwritten integrator for now, in which I can wedge my inelegant `if` condition from above. Thanks!

**Comment by ChrisRackauckas** [comment]
You can also just write the same model in DifferentialEquations.jl. 

```julia
	if u[2, 1] < -1
		u[2, 2] = 0
	end
```

that's a DiscreteCallback. You can just do that if that's what you want. 

For your last model, the solution is just to write a more numerically stable version by bouncing until a limit. That is:

```julia
floor_cond(u, t, int) = u[2, 1] + 1
function floor_aff!(int) 
  int.u[2, 2] *= -0.5
  if int.u[2, 2] < 1e-6
    int.u[2, 2] = 0
  end
end
```

so that it has finitely many bounces.

**Comment by dmillard** [comment]
I see. I had steered away from DiscreteCallback because there was no VectorContinuousCallback analogue, as far as I could tell, and I have ~400 events to check. I'll profile and see how it looks.

Thanks for the correction to the numerically stable version! Happy for this issue to be closed, unless you want to use it to track anything here.

**Comment by ChrisRackauckas** [comment]
A new tutorial on callback handling for exactness and accumulation points was added. I think you'd appreciate it as the solution here, since it describes the underlying floating point issues and what you should do to avoid potential issues. The code ends up being:

```julia
using OrdinaryDiffEq, Plots
function dynamics!(du, u, p, t)
	du[1] = u[2]
	du[2] = p[1] * -9.8
end
floor_cond(u, t, int) = u[1]
function floor_aff!(int)
    int.u[2] *= -0.5
    if int.dt > 1e-12
        set_proposed_dt!(int,(int.t-int.tprev)/100)
    else
        int.u[1] = 0
        int.u[2] = 0
        int.p[1] = 0
    end
    int.p[2] += 1
    int.p[3] = int.t
end
floor_event = ContinuousCallback(floor_cond, floor_aff!)
u0 = [1.0,0.0]
p = [1.0,0.0,0.0]
prob = ODEProblem{true}(dynamics!, u0, (0., 2.), p)
sol = solve(prob, Tsit5(), callback=floor_event)
plot(sol)
@show p # [0.0, 41.0, 1.355261854357056]
savefig("bounce_accumulation.png")

p1 = plot(sol,vars=1,tspan=(1.25,1.40))
p2 = plot(sol,vars=1,tspan=(1.35,1.36))
p3 = plot(sol,vars=1,tspan=(1.354,1.35526))
p4 = plot(sol,vars=1,tspan=(1.35526,1.35526185))
plot(p1,p2,p3,p4)
savefig("bounce_accumulation_zoom.png")
```

![bounce_accumulation](https://user-images.githubusercontent.com/1814174/122675142-15799d00-d1a6-11eb-9962-42cbeee1bc98.png)

![bounce_accumulation_zoom](https://user-images.githubusercontent.com/1814174/122675145-17436080-d1a6-11eb-8958-76ae4ca2ba7e.png)
