### ISSUE TITLE
DifferentialEquations or OrdinaryDiffEq  packages?

### ISSUE THREAD

**Issue by Peter-Jolly** [SciML/DifferentialEquations.jl#793]
I have been using the package "OrdinaryDiffEq" for a little over a year with good effect (solve a system of 123 ODE's repetitively). I decided to switch to DifferentialEquations to see what would happen, and I am happy to say it also worked well with similar performance. It seemed to me the DifferentialEquations compiles faster. Could someone comment on which is the preferred package? Thanks.

**Comment by ChrisRackauckas** [comment]
It's the same: DifferentialEquations.jl is just a metapackage that pulls together OrdinaryDiffEq, Sundials, LSODA, etc. into a single interface and documentation. But when you use `Tsit5` from DifferentialEquations.jl, it's just OrdinaryDiffEq.jl. OrdinaryDiffEq.jl will usually have faster precompiles because of this.

**Comment by Peter-Jolly** [comment]
Thanks for clarification.
