### ISSUE TITLE
error running using --compiled-modules=no command line option

### ISSUE THREAD

**Issue by salbert83** [SciML/DifferentialEquations.jl#813]
I generated the error in test.txt when running "julia --compiled-modules=no my_test.jl"  The only line in the file was, "using DifferentialEquations" 

[test.txt](https://github.com/SciML/DifferentialEquations.jl/files/7471816/test.txt)

**Comment by ChrisRackauckas** [comment]
Is this for the interpreter?

@chriselrod it's pointing to FastBroadcast.jl

**Comment by salbert83** [comment]
Perhaps.  I haven’t come across this error with other modules (yet).

Thank you for your quick responses to my issues.

Regards,

Sam Albert

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by chriselrod** [comment]
Generated functions normally don't have world age issues inside modules, because they all get frozen to the same world age when the module precompiles.

Running without precompiled modules suddenly means that the order of function definitions within a module matter.

Unfortunately, MPI.jl recommends people use `--compiled-modules=no`.

**Comment by ChrisRackauckas** [comment]
Great
