### ISSUE TITLE
how to get different random noise

### ISSUE THREAD

**Issue by yuyuexi** [SciML/DifferentialEquations.jl#883]
Hi, I am using `DifferentialEquations.jl` in my project, and find this pkg is awesome!

I implement a ensemble problem, while i find that the solutions have same random noise `W`.

I checked 1) the random seeds, they are different; 2) the results, they are different.

A sample code is as:
```julia
using DifferentialEquations

t0 = 0
t1 = 1
dt = 0.01
num_traj = 2

function f(du,u,p,t)
    return du .= - 5. * u
end

function g(du,u,p,t) 
    return du .= 2.
end

u0 = [1.0]

prob = SDEProblem(f,g,u0,(t0,t1),noise=WienerProcess(0.0,0.0,0.0))
ensemble_prob = EnsembleProblem(prob)

sols = solve(ensemble_prob; trajectories=num_traj,dt=dt,save_noise=true,adaptive=false);

@show sols[1].W.W ≈ sols[2].W.W;

@show sols[1].seed == sols[2].seed;
@show sols[1].u ≈ sols[2].u;
```
In my device, it shows
```
(sols[1]).W.W ≈ (sols[2]).W.W = true
(sols[1]).seed == (sols[2]).seed = false
(sols[1]).u ≈ (sols[2]).u = false
```
I am using Julia 1.7.2, and [0c46a032] DifferentialEquations v7.1.0.

My question are 
1) Why do they have the same noise `W`? 
2) Why do those same `W` give back different results?
3) How can we obtain different noise?

Many thanks!

**Comment by yuyuexi** [comment]
I find that the noise are randomly selected, while the record are the same. Different noise can be saved by setting `safetycopy=true`.

**Comment by ChrisRackauckas** [comment]
Quick explanation of what's going on here. `prob = SDEProblem(f,g,u0,(t0,t1),noise=WienerProcess(0.0,0.0,0.0))` defines an SDE with the noise process `WienerProcess(0.0,0.0,0.0)`. Now if you do an ensemble of solves with that, they will all have the same noise process by definition. If you don't want that, then don't define them all to have the same noise process. For example, this would be done by making the prob function:

```julia
function prob_func(i)
  SDEProblem(f,g,u0,(t0,t1),noise=WienerProcess(0.0,0.0,0.0))
end
```

which creates a new noise process for each solve. Since each of your solves has the same noise process, they generate the same result. Direct setting of the noise process overrides the RNG object because there is no RNG after the first solve: the noise process will fill in its values and the subsequent solves will just reuse the same values.

`safetycopy=true` is equivalent to:

```julia
function prob_func(i)
  deepcopy(prob)
end
```

and thus since it's a completely new problem, it has a new noise process, and thus gets different results.

Hope that makes sense.
