### ISSUE TITLE
Advection diffusion example on Julia website has an error

### ISSUE THREAD

**Issue by rs240291** [SciML/DifferentialEquations.jl#919]
The example "Advection diffusion" on the Julia website (https://docs.juliahub.com/Kinetic/wrVmu/0.7.4/eg_advection/) has an error as I was trying to reproduce that code in order to learn the language.
On that website it has: ib = KitBase.IB(w0, prim0, prim0, w0, prim0, prim0).
But the above line gives an error:
ERROR: MethodError: no method matching KitBase.IB(::Float64, ::Vector{Float64}, ::Vector{Float64}, ::Float64, ::Vector{Float64}, ::Vector{Float64})
Closest candidates are:
  KitBase.IB(::Any, ::Any) at ~/.julia/packages/KitBase/X6u38/src/Type/struct_ib.jl:20
  KitBase.IB(::Function, ::T, ::NamedTuple) where T at ~/.julia/packages/KitBase/X6u38/src/Type/struct_ib.jl:15
  KitBase.IB(::Any) at ~/.julia/packages/KitBase/X6u38/src/Type/struct_ib.jl:20
Stacktrace:
 [1] top-level scope
   @ REPL[26]:1
 [2] top-level scope
   @ ~/.julia/packages/CUDA/DfvRa/src/initialization.jl:52

Please answer what is the problem!

**Comment by ChrisRackauckas** [comment]
That is not DifferentialEquations.jl. And further, it's not even a library in the entire SciML ecosystem. https://docs.sciml.ai/Overview/stable/ is a documentation of all of our libraries, and Kinetic is not in there. Please ask the authors of Kinetic.jl about their library.

P.S. I would assume the issue is that you're looking at old documentation. The documentation of the latest release is different (https://xiaotianbai.com/Kinetic.jl/stable/eg_advection/) and most likely that is the one that's functional. I would recommend trying that, that YMMV and I cannot say I know anything about that library.
