### ISSUE TITLE
How to store the intermediate variables in the differentialequation function

### ISSUE THREAD

**Issue by KennethAnn** [SciML/DifferentialEquations.jl#933]
Dear all authors:
    Here I face a troublesome problem when I use DifferentialEquations.jl to do some modeling tasks. In my tasks, there are many important intermediate variables which are the expression of u, such as the s and h in the code below. And then I use such intermediate variables to be the component of the differential equations. The major concern is that such intermediate variables need to be exported for Bayesian inference and analysis, however, the only way I have is to define a new function to calculate the intermediate variables by solutions. Is there any simple method to export the intermediate variables (s and h) from the current function?

```julia
function EarthModel!(du, u, p, t)
    x, y = u
    s = x^2 + y
    h = x + y^2
    du[1] = s
    du[2] = h
end
```

**Comment by ChrisRackauckas** [comment]
> Is there any simple method to export the intermediate variables (s and h) from the current function?

You calculate `f` about 7 times per step. Calculating it one more time means that you're talking about an optimization of at most 12.5%, if this was the absolute most expensive part of the calculation and nothing else came close. Are you sure this is the top optimization opportunity in your code?

The answer is, not really, because most of the `f` evaluations are not on save points. In fact, it's almost guaranteed that none are, so you're not saving any computation by saving those evaluations. ModelingToolkit does have some features around this:

https://docs.sciml.ai/ModelingToolkit/stable/tutorials/ode_modeling/

but it's just lazy post-construction because of this. In the end, because solve `f`s are not at the same time as save `t`s, it's an imagined optimization which only makes sense for Euler.
