### ISSUE TITLE
Can't precompile DifferentialEquations.jl, gets stuck on BoundaryValueDiffEq.jl

### ISSUE THREAD

**Issue by akriegman** [SciML/DifferentialEquations.jl#972]
I'm trying to install DifferentialEquations.jl, but every time I try it gets stuck on precompiling BoundaryValueDiffEq.jl. I've tried in Pluto and on the REPL. I tried deleting `~/.julia/packages` and reinstalling everything. I also tried deleting `~/.julia/compiled`. I was able to successfully install the latest version of BoundaryValueDiffEq, but DifferentialEquations uses v2.11.0. So maybe the problem is more with this older version of BoundaryValueDiffEq, or maybe it's with the interaction between the packages, or maybe the problem is just that DifferentialEquations is using this older version.

My diagnostics:
```
OS: Ubuntu 20.04.6 LTS x86_64
Host: 81X2 IdeaPad Flex 5 14ARE05
Kernel: 5.15.0-76-lowlatency
Uptime: 18 days, 7 hours, 13 mins
CPU: AMD Ryzen 7 4700U with Radeon Graphics (8) @ 2.000GHz
GPU: AMD ATI 04:00.0 Renoir
Memory: 9164MiB / 15349MiB

julia version 1.9.0-beta2
```

**Comment by akriegman** [comment]
Well, I updated my Julia version and now it works. Sorry for wasting your time guys.

**Comment by eRedekopp** [comment]
I had this same problem while using the version of Julia that ships with the 'julia' Docker container on Docker Hub. I was able to fix it by using a different base container and installing Julia from the official website instead of using the version that ships with the container. This is despite the two different Julia builds having identical version numbers.

**Comment by ChrisRackauckas** [comment]
Some Linux versions build Julia with the wrong LLVM. I think NixOS did that. They need to be scolded. I understand why they do it, because they use whatever LLVM version is in their package repository, but Julia includes a specific LLVM version which also has patches, and that has to be used for correctness. That could be the issue.
